apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-docker-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-website
  template:
    metadata:
      labels:
        app: cicd-website
    spec:
      containers:
      - name: cicd-docker-container
        image: godratan/cicd-docker-website:latest
        ports:
        - containerPort: 80
